version: '3.8'

services:
  db:
    image: postgres:16
    container_name: taskmanager_db
    enviroment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: